name: githubaction example

on:
  push:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      file_changed: ${{ steps.check.outputs.file_changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for specific file changes
        id: check
        run: |
          if git diff 15322dc0f749a86258f6ea377fc29cf769b37e51 6f1042392f8e3638d1b67f8792e98c49c24549ca; then
            echo "file_changed=true" >> $GITHUB_OUTPUT
          else
            echo "file_changed=false" >> $GITHUB_OUTPUT
          fi

  Print:
    needs: build
    if: ${{ needs.build.outputs.file_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "hello world"
