name: githubaction example

on:
  push:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value2: [A,B]  
    outputs:
      file_changed: ${{ steps.check.outputs.file_changed }}  # Reference output
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for specific file changes
        id: check
        run: |
          # Check if there are specific file changes
          #if [ 20 -gt 10 ]; then
          if git diff HEAD~1 HEAD | grep -q '.README.md'; then
            echo "file_changed_${{ matrix.value2 }}=true" >> $GITHUB_OUTPUT  # Set output correctly
          else
            echo "file_changed_${{ matrix.value2 }}=false" >> $GITHUB_OUTPUT  # Set output correctly
          fi

      - name: Display output
        run: echo "file_changed=${{ steps.check.outputs.file_changed }}"  # Display the output

  Print:
    needs: build
    if: ${{ needs.build.outputs.file_changed == 'true' }}  # Check the output
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "Deploy job is executed because file_changed is true."
