name: githubaction example

on:
  push:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      file_changed: ${{ steps.check.outputs.file_changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for specific file changes
        id: check
        run: |
          if git diff HEAD~1 HEAD | grep -q '.README.md'; then
            echo "file_changed=true" >> $GITHUB_OUTPUT
          else
            echo "file_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: display env
        run: echo ${{ env.file_changed }}

  Print:
    needs: build
    if: ${{ needs.build.outputs.file_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "hello world"
