name: Call Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  call-ci:
    uses: anusha414/reusable-demo-workflows/.github/workflows/matrix.yml@master  # Adjust the username and branch as needed
    with:
      combinations: '[{"node-version": "14", "os-version": "ubuntu-latest"}, {"node-version": "16", "os-version": "windows-latest"}]'
